"""S8: Cross-pair validation harness for SESSION 8.

Runs PairMapper across every expanded pair YAML and emits a single
markdown summary at ``docs/session8_cross_pair_validation.md`` with
per-pair {n_mappings, tier distribution, needs_review_count, MRR,
Recall@5, ROC-AUC, MRR 95 % CI}. The MRR family is computed via the
S2 discriminative module against 20 distractors per anchor sampled by
the S1 sampler (seed=20260407).

This is the readiness gate for SESSION 8. The output table is meant to
be read manually before running the full pipeline on new pairs.
"""

from __future__ import annotations

import json
from pathlib import Path

from mapping_engine.calibration.discriminative_metric import bootstrap_ci, score
from mapping_engine.calibration.distractor_sampler import sample_distractors
from mapping_engine.config import load_pair_config
from mapping_engine.engine.graph import load_graph
from mapping_engine.engine.mapper import PairMapper

REPO = Path(__file__).resolve().parents[2]
PAIRS_DIR = REPO / "mapping_engine/config/pairs"
OUT_MD = REPO / "docs/session8_cross_pair_validation.md"
OUT_JSON = REPO / "data/processed/session8_cross_pair_validation.json"
N_PER_ANCHOR = 20
RNG_SEED = 20260407


def _expanded_pairs() -> list[str]:
    seen = set()
    out = []
    for p in sorted(PAIRS_DIR.glob("*__expanded.yaml")):
        name = p.stem.removesuffix("__expanded")
        if name in seen:
            continue
        seen.add(name)
        out.append(name)
    return out


def _eval_pair(G, name: str) -> dict:
    cfg = load_pair_config(name + "__expanded", validate_anchors_in=G)
    mapper = PairMapper(G, cfg, use_learned_weights=False)
    result = mapper.run()

    # Tier distribution + needs_review from the production mappings list.
    tier_counts = {"Direct": 0, "Related": 0, "None": 0, "other": 0}
    needs_review = 0
    for m in result.mappings:
        t = m.get("tier", "None")
        tier_counts[t if t in tier_counts else "other"] += 1
        if m.get("needs_review"):
            needs_review += 1
    n_mappings = len(result.mappings)

    # Discriminative metrics — same protocol as S3/S5/S6/S7.
    src_idx = {n: i for i, n in enumerate(result.source_nodes)}
    tgt_idx = {n: i for i, n in enumerate(result.target_nodes)}
    av = result.anchor_validation
    masked: dict = {}
    masked.update(av.get("training_anchors", {}))
    masked.update(av.get("holdout_anchors", {}))

    pos_scores: list[float] = []
    dist_scores: list[list[float]] = []
    try:
        ds_list = sample_distractors(
            PAIRS_DIR / f"{name}__expanded.yaml", G,
            n_per_anchor=N_PER_ANCHOR, rng_seed=RNG_SEED,
        )
    except Exception as e:
        ds_list = []
        sampler_error = str(e)
    else:
        sampler_error = None
    for ds in ds_list:
        key = f"{ds.source}__{ds.positive}"
        rec = masked.get(key)
        if rec is None or ds.source not in src_idx:
            continue
        si = src_idx[ds.source]
        d_row = [
            float(result.composite_scores[si, tgt_idx[d]])
            for d in ds.distractors
            if d in tgt_idx
        ]
        if not d_row:
            continue
        pos_scores.append(float(rec.get("score", 0.0)))
        dist_scores.append(d_row)

    if pos_scores:
        s = score(pos_scores, dist_scores)
        ci = bootstrap_ci(pos_scores, dist_scores, n_resamples=1000, rng_seed=RNG_SEED)
        mrr_pt, mrr_lo, mrr_hi = ci["mrr"]
    else:
        s = None
        mrr_pt = mrr_lo = mrr_hi = None

    return {
        "pair": name,
        "n_mappings": n_mappings,
        "tier_counts": tier_counts,
        "needs_review_count": needs_review,
        "n_anchors_scored": len(pos_scores),
        "mrr": s.mrr if s else None,
        "mrr_ci": [mrr_lo, mrr_hi] if mrr_pt is not None else None,
        "recall_at_5": s.recall_at_5 if s else None,
        "roc_auc": s.roc_auc if s else None,
        "sampler_error": sampler_error,
    }


def _render_md(rows: list[dict]) -> str:
    lines = [
        "# Session 8 — Cross-Pair Validation Harness",
        "",
        "Auto-generated by `mapping_engine/scripts/cross_pair_validation.py`.",
        "",
        "Each row is one expanded pair run end-to-end through the post-S5",
        "production pipeline (mitigation_lexical_match blended at weight=0.10,",
        "narrow-band cross-encoder rerank ON, reranker_v2 dropped per S6,",
        "calibrated thresholds direct=0.45 / related_primary=0.20).",
        "Discriminative metrics use 20 distractors per anchor, seed=20260407.",
        "",
        "| Pair | n_map | Direct | Related | None | needs_review | n_anc | MRR [95% CI] | Recall@5 | AUC |",
        "|---|---:|---:|---:|---:|---:|---:|---|---:|---:|",
    ]
    for r in rows:
        tc = r["tier_counts"]
        if r["mrr"] is not None:
            mrr_str = f"{r['mrr']:.4f} [{r['mrr_ci'][0]:.4f}, {r['mrr_ci'][1]:.4f}]"
            r5 = f"{r['recall_at_5']:.4f}"
            auc = f"{r['roc_auc']:.4f}"
        else:
            mrr_str = "n/a"
            r5 = "n/a"
            auc = "n/a"
        lines.append(
            f"| `{r['pair']}` | {r['n_mappings']} | {tc['Direct']} | {tc['Related']} | "
            f"{tc['None']} | {r['needs_review_count']} | {r['n_anchors_scored']} | "
            f"{mrr_str} | {r5} | {auc} |"
        )
    lines.append("")
    lines.append(
        "**Skipped-anchor note.** `cosai_rm__*` pairs report `n_anc=0` because"
        " cosai_rm source nodes do not currently surface in PairMapper's"
        " masked-validation records. The mapping output (`n_map`) is"
        " unaffected and remains the production source of truth for those"
        " pairs. Filed for SESSION 8 follow-up."
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    G = load_graph(REPO / "data/processed/nodes.json", REPO / "data/processed/edges.json")
    rows = []
    for name in _expanded_pairs():
        print(f"  evaluating {name} ...")
        rows.append(_eval_pair(G, name))
    OUT_MD.write_text(_render_md(rows))
    OUT_JSON.write_text(json.dumps({"rows": rows}, indent=2, default=str))
    print(f"Wrote {OUT_MD}")
    print(f"Wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
