"""S12: distractor count sweep.

Re-runs the discriminative metric collection across n_per_anchor in
{10, 20, 40, 80} on the post-S11 pipeline and writes a markdown
diagnostic with aggregate MRR + 1000-resample bootstrap CI per n. The
canonical evaluation n is settled as: keep n=20 if its CI width is
within 1.5x the n=80 width; otherwise pick the smallest n whose CI
width is within 1.2x the n=80 width.
"""

from __future__ import annotations

from pathlib import Path

from mapping_engine.calibration.discriminative_metric import bootstrap_ci, score
from mapping_engine.engine.graph import load_graph
from mapping_engine.scripts import eval_discriminative_baseline as edb

REPO = Path(__file__).resolve().parents[2]
SWEEP_NS = (10, 20, 40, 80)


def main() -> None:
    G = load_graph(REPO / "data/processed/nodes.json", REPO / "data/processed/edges.json")
    rows = []
    for n in SWEEP_NS:
        edb.N_PER_ANCHOR = n  # patch the constant the helper reads
        all_pos: list[float] = []
        all_dist: list[list[float]] = []
        for name in edb._expanded_pair_configs():
            pos, dist, _ = edb._collect_pair(G, name)
            all_pos.extend(pos)
            all_dist.extend(dist)
        s = score(all_pos, all_dist)
        ci = bootstrap_ci(all_pos, all_dist, n_resamples=1000, rng_seed=edb.RNG_SEED)
        mrr_lo, mrr_hi = ci["mrr"][1], ci["mrr"][2]
        width = mrr_hi - mrr_lo
        rows.append(
            {"n": n, "n_anchors": s.n_anchors, "mrr": s.mrr,
             "ci_lo": mrr_lo, "ci_hi": mrr_hi, "width": width,
             "auc": s.roc_auc}
        )
        print(f"n={n} anchors={s.n_anchors} mrr={s.mrr:.4f} "
              f"CI=[{mrr_lo:.4f},{mrr_hi:.4f}] width={width:.4f}")

    width_80 = next(r["width"] for r in rows if r["n"] == 80)
    width_20 = next(r["width"] for r in rows if r["n"] == 20)
    if width_20 <= 1.5 * width_80:
        decision_n = 20
        rationale = (
            f"n=20 CI width {width_20:.4f} ≤ 1.5 × n=80 width "
            f"{width_80:.4f} = {1.5*width_80:.4f}; KEEP n=20."
        )
    else:
        decision_n = next(
            (r["n"] for r in rows if r["width"] <= 1.2 * width_80),
            80,
        )
        rationale = (
            f"n=20 CI width {width_20:.4f} > 1.5 × n=80 width "
            f"{width_80:.4f}; smallest n with width ≤ 1.2 × n=80 = {decision_n}."
        )

    lines = ["# Distractor count sweep (S12)\n"]
    lines.append(
        "Generated by `mapping_engine/scripts/sweep_distractor_count.py`. "
        "All metrics use 1000-resample bootstrap CIs at fixed seed.\n"
    )
    lines.append("| n_per_anchor | n_anchors | MRR | CI | width | ROC-AUC |")
    lines.append("|---:|---:|---:|---|---:|---:|")
    for r in rows:
        lines.append(
            f"| {r['n']} | {r['n_anchors']} | {r['mrr']:.4f} "
            f"| [{r['ci_lo']:.4f}, {r['ci_hi']:.4f}] | {r['width']:.4f} | {r['auc']:.4f} |"
        )
    lines.append("")
    lines.append(f"## Decision\n\n**Canonical n = {decision_n}.** {rationale}\n")

    out = REPO / "docs/diagnostics/distractor_count_sweep.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Wrote {out}")
    print(f"DECISION: canonical n = {decision_n}")


if __name__ == "__main__":
    main()
